name: Deploy to Google Cloud Run

on:
  workflow_run:
    workflows: ["Python package"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/g2-sentiment-analysis:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/g2-sentiment-analysis:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy g2-sentiment-analysis \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/g2-sentiment-analysis:$GITHUB_SHA \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated